[workspace]
resolver = "2"

members = [
    "mattis",
    "mattis-bitboard",
    "mattis-types",
    "mattis-tablegen",
    "mattis-uci",
]

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"
