[package]
name = "mattis-tablegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mattis-types = { path = "../mattis-types" }
mattis-bitboard = { path = "../mattis-bitboard" }
rand = "0.8.5"
